// presentation/sections/home/HomeSections.constants.ts
// Fallback default home sections structure and ordering using SectionDTO.

import type { SectionDTO } from "../../../application/dto/SectionDTO";

export const DEFAULT_HOME_SECTIONS: readonly SectionDTO[] = [
  {
    id: "hero",
    pageId: "home",
    type: "hero",
    title: "Hero",
    content: {},
    order: 0,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "telemetry",
    pageId: "home",
    type: "telemetry",
    title: "Telemetry",
    content: {},
    order: 1,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "impact",
    pageId: "home",
    type: "impact",
    title: "Impact",
    content: {},
    order: 2,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "experience",
    pageId: "home",
    type: "experience",
    title: "Experience",
    content: {},
    order: 3,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "capabilities",
    pageId: "home",
    type: "capabilities",
    title: "Capabilities",
    content: {},
    order: 4,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "credentials",
    pageId: "home",
    type: "credentials",
    title: "Credentials",
    content: {},
    order: 5,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "contact",
    pageId: "home",
    type: "contact",
    title: "Contact",
    content: {},
    order: 6,
    isVisible: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
